# Generated by Django 3.1.5 on 2021-02-13 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='loanDataId',
        ),
        migrations.AddField(
            model_name='account',
            name='loanData',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CustomApi.userloandata'),
        ),
    ]
