# Generated by Django 3.1.5 on 2021-01-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomApi', '0002_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='approved',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
