# Generated by Django 3.1.5 on 2021-01-10 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomApi', '0004_account_loandata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=128, verbose_name='email'),
        ),
    ]
